PHPLIB-1122: Support Document and PackedArray objects in public APIs (#1077)
Excluding tests, most changes were concentrated in functions.php. A document_to_array() function was introduced to make it easier to access document values as arrays. This is mainly used by other utility functions (e.g. checking for dollar prefixed keys) but also ended up being used in the Find operation for handling the "modifiers" option.

Adds tests for using Document and PackedArray objects in operations.

Beyond handling of document/array types, this also filled gaps in test coverage for:

 * Validation for IndexInput key/name options
 * Passing a MongoDB\Driver\Command directly to DatabaseCommand
 * is_last_pipeline_operator_write()

* Use elseif for checking Serializable after Document or PackedArray

Processing a Document and PackedArray will yield an array, so we can avoid a redundant Serializable check by using elseif.

* Use array_key_first() and refactor is_pipeline() to use is_first_key_operator()

This introduces a dependency on symfony/polyfill-php73 and bumps both polyfill packages to the latest minor version for consistency.

The doc block for is_first_key_operator() was revised to note its additional purpose for validating pipeline stages.

* Test is_first_key_operator() with empty and packed arrays

* Note an edge case where is_pipeline() may throw InvalidArgumentException

* Add type annotations to assist static analysis

* Use psalm-var annotation and fix phpcs errors

* Regenerate psalm baseline

This suppresses a new error in BulkWrite pertaining to a variable previously checked by is_first_key_operator() and is_pipeline().

```
ERROR: MixedArgument - src/Operation/BulkWrite.php:341:45 - Argument 2 of MongoDB\Driver\BulkWrite::update cannot be mixed, expecting array<array-key, mixed>|object (see https://psalm.dev/030)
                    $bulk->update($args[0], $args[1], $args[2]);

  The type of $args[1] is sourced from here - vendor/vimeo/psalm/stubs/CoreGenericFunctions.phpstub:154:12
 * @return (TArray is array<empty,empty> ? false : (TArray is non-empty-array ? TValue : TValue|false))
```

Other changes to the baseline are removals for obsolete errors.