Regenerate psalm baseline
This suppresses a new error in BulkWrite pertaining to a variable previously checked by is_first_key_operator() and is_pipeline().

```
ERROR: MixedArgument - src/Operation/BulkWrite.php:341:45 - Argument 2 of MongoDB\Driver\BulkWrite::update cannot be mixed, expecting array<array-key, mixed>|object (see https://psalm.dev/030)
                    $bulk->update($args[0], $args[1], $args[2]);

  The type of $args[1] is sourced from here - vendor/vimeo/psalm/stubs/CoreGenericFunctions.phpstub:154:12
 * @return (TArray is array<empty,empty> ? false : (TArray is non-empty-array ? TValue : TValue|false))
```

Other changes to the baseline are removals for obsolete errors.